name: Run Scraping Automation Script

on:
  push:
    branches:
      - main
  schedule:
    # Run at 10:00 AM and 4:00 PM every day
    - cron: '0,6 * * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      

      - name: Run Python Automation script
        run: |
          python mainpy

      
        - name: Commit changes
          run: |
            git config --global user.name 'github-actions'
            git config --global user.email 'github-actions@github.com'
            git add python_log.txt
            git commit -m 'Update log file'
            git push
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    